services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: .
    restart: unless-stopped
    environment:
      postgres_username: postgres
      postgres_password: postgres
      postgres_host: postgres
      postgres_port: 5432
      secret_key: str
    ports:
      - 8000:8000
    depends_on: 
      - postgres

volumes:
  postgres-data:
